### ISSUE TITLE
Basic CSS

### ISSUE THREAD

**Issue by vasystus** [fac24/week1-alex-hallie-hussain-sonia#4]
Add a basic CSS

**Comment by sonianb** [comment]
### Some suggestions 

I think that since we're going for a Scandinavia-inspired theme, it should be as minimalistic and clean as possible. In this spirit, I would suggest: 
- removing the box shadow the posts
- choose a plain background for the posts instead of the radiant because now it feels a bit too much with both the box shadow and the radiant colours (that's how I see it at least 😅 )
- I really like the background colour and the colour of the submit button when you hover, what if we keep these two colours as our two basic colours?

**Comment by vasystus** [comment]
We could remove them any time. But the priority at the moment(my opinion) with CSS - fixing the broken code. I'm trying to understand, how code I'm pushing still doesn't have matching classes with yours?
